language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - yarn build

deploy:
  provider: pages
  cleanup: true
  github_token: '$GITHUB_TOKEN'
  keep_history: true
  local_dir: docs
  on:
    branch: master
